version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: customer_unique_id
        tests:
          - not_null

  - name: dim_sellers
    columns:
      - name: seller_id
        tests:
          - not_null
          - unique

  - name: dim_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: date_id
        tests:
          - not_null
          - unique

  - name: fact_orders
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: seller_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_sellers')
              field: seller_id
      - name: order_status
        tests:
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'created', 'approved']
      - name: price
        tests:
          - not_null