{{ config(materialized='incremental', unique_key='HOST_ID') }}

SELECT
    HOST_ID,
    REPLACE(HOST_NAME, ' ', '_') AS HOST_NAME,
    HOST_SINCE,
    IS_SUPERHOST,
    RESPONSE_RATE,
    CASE 
    WHEN RESPONSE_RATE > 95 THEN 'EXCELLENT'
    WHEN RESPONSE_RATE >= 80 AND RESPONSE_RATE <= 95 THEN 'GOOD'
    WHEN RESPONSE_RATE >= 60 AND RESPONSE_RATE < 80 THEN 'MODERATE'
    WHEN RESPONSE_RATE >= 40 AND RESPONSE_RATE < 60 THEN 'LOW'
    ELSE 'VERY LOW'
    END AS RESPONSE_RATE_QUALITY,
    CREATED_AT
FROM
    {{ ref('bronze_hosts') }}